/// Flutter icons Moki
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Moki
///      fonts:
///       - asset: fonts/Moki.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Moki {
  Moki._();

  static const _kFontFam = 'Moki';
  static const String? _kFontPkg = null;

  static const IconData ri_play_circle_line = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ri_search_line = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ri_home_2_fill = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ri_account_circle_line = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
